# Generated by Django 3.2.3 on 2021-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210519_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Greeting_title', models.CharField(default='Hello', max_length=40)),
                ('Greeting_name', models.CharField(default='I AM DR. KRISHNA REGMI', max_length=40)),
                ('Greeting_desc', models.CharField(default='& I am a Oral Maxillofacial Surgeon.', max_length=70)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
            ],
        ),
        migrations.AddField(
            model_name='personal_details',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='training_and_advance_skill_slider',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images'),
        ),
    ]
