# Generated by Django 3.2.3 on 2021-05-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210519_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socail_media',
            new_name='Social_media',
        ),
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name_plural': 'About me'},
        ),
        migrations.AlterModelOptions(
            name='clinic_timing',
            options={'verbose_name_plural': 'Clinic timing'},
        ),
        migrations.AlterModelOptions(
            name='contact_me',
            options={'verbose_name_plural': 'Contact me'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='greeting',
            options={'verbose_name_plural': 'Greeting'},
        ),
        migrations.AlterModelOptions(
            name='latest_news',
            options={'verbose_name_plural': 'Latest news'},
        ),
        migrations.AlterModelOptions(
            name='my_skills',
            options={'verbose_name_plural': 'My skills'},
        ),
        migrations.AlterModelOptions(
            name='other_professional_skills',
            options={'verbose_name_plural': 'Other professional skills'},
        ),
        migrations.AlterModelOptions(
            name='personal_details',
            options={'verbose_name_plural': 'Personal details'},
        ),
        migrations.AlterModelOptions(
            name='social_media',
            options={'verbose_name_plural': 'Social media'},
        ),
        migrations.AlterModelOptions(
            name='training_and_advance_skill',
            options={'verbose_name_plural': 'Training_and_advance_skill'},
        ),
        migrations.AlterModelOptions(
            name='training_and_advance_skill_slider',
            options={'verbose_name_plural': 'Training and advance skill slider'},
        ),
        migrations.AlterModelOptions(
            name='work_experience',
            options={'verbose_name_plural': 'Work experience'},
        ),
        migrations.AlterModelOptions(
            name='work_experience_location',
            options={'verbose_name_plural': 'Work experience location'},
        ),
    ]
